# **Data Insepection**

In [4]:
import pandas as pd

df = pd.read_csv("../dataset/tech_mental_health_burnout.csv")
print(df)

        age      gender            job_role  experience_years company_size  \
0        50      Female   Backend Developer               7.8        Large
1        36        Male  Frontend Developer               1.8     Mid-size
2        29        Male              DevOps               2.5          MNC
3        42      Female   Backend Developer               1.5     Mid-size
4        40      Female  Frontend Developer               3.4        Large
...     ...         ...                 ...               ...          ...
149995   54      Female              DevOps               6.8     Mid-size
149996   52        Male   Software Engineer               5.7      Startup
149997   36        Male   Backend Developer               2.2     Mid-size
149998   35        Male  Frontend Developer               3.7        Large
149999   36  Non-binary              DevOps               5.0     Mid-size

       work_mode  work_hours_per_week  overtime_hours  meetings_per_day  \
0         Hybrid                 45.0             0.0               5.0
1         Remote                 56.0             4.0               6.0
2         Hybrid                 43.0             2.0               6.0
3         Hybrid                 57.0             9.0               4.0
4         Remote                 49.0             0.0               3.0
...          ...                  ...             ...               ...
149995    Remote                 41.0             4.0               5.0
149996    Hybrid                 42.0             4.0               5.0
149997    Hybrid                 38.0             6.0               2.0
149998    Hybrid                 41.0             9.0               6.0
149999    Hybrid                 56.0             4.0               2.0

        deadlines_missed  ...  screen_time_hours  caffeine_intake  \
0                      0  ...                8.6                1
1                      0  ...               11.5                4
2                      3  ...                6.8                3
3                      1  ...               10.2                5
4                      4  ...               11.9                5
...                  ...  ...                ...              ...
149995                 3  ...               12.0                2
149996                 2  ...                6.8                1
149997                 0  ...                8.9                5
149998                 5  ...               10.1                3
149999                 0  ...                5.6                4

        social_support_score  has_therapy  stress_level  anxiety_score  \
0                        4.4            0           4.8            4.3
1                        4.1            0           6.7            4.8
2                        6.5            0           4.5            4.0
3                        2.5            0           6.1            5.8
4                        4.6            0           7.2            5.9
...                      ...          ...           ...            ...
149995                   7.3            0           6.9            2.7
149996                   3.2            0           4.6            5.3
149997                   8.5            0           7.9            4.2
149998                   5.6            1           5.7            5.4
149999                   7.8            0           5.0            3.1

        depression_score  burnout_score  burnout_level  \
0                    2.6            1.0            Low
1                    4.6            3.7       Moderate
2                    2.5            1.0            Low
3                    1.8            3.6       Moderate
4                    2.4            3.5            Low
...                  ...            ...            ...
149995               3.2            1.2            Low
149996               3.3            1.1            Low
149997               3.9            2.8            Low
149998               3.4            1.5            Low
149999               2.2            1.0            Low

        seeks_professional_help
0                             0
1                             0
2                             0
3                             0
4                             0
...                         ...
149995                        0
149996                        0
149997                        0
149998                        0
149999                        0

[150000 rows x 25 columns]

In [14]:
print("Shape:",df.shape)

Shape: (150000, 25)

In [15]:
print("Columns:",df.columns.tolist())

Columns: ['age', 'gender', 'job_role', 'experience_years', 'company_size', 'work_mode', 'work_hours_per_week', 'overtime_hours', 'meetings_per_day', 'deadlines_missed', 'job_satisfaction', 'manager_support', 'work_life_balance', 'sleep_hours', 'physical_activity_days', 'screen_time_hours', 'caffeine_intake', 'social_support_score', 'has_therapy', 'stress_level', 'anxiety_score', 'depression_score', 'burnout_score', 'burnout_level', 'seeks_professional_help']

In [18]:
print(df.dtypes)

age                          int64
gender                      object
job_role                    object
experience_years           float64
company_size                object
work_mode                   object
work_hours_per_week        float64
overtime_hours             float64
meetings_per_day           float64
deadlines_missed             int64
job_satisfaction           float64
manager_support            float64
work_life_balance          float64
sleep_hours                float64
physical_activity_days       int64
screen_time_hours          float64
caffeine_intake              int64
social_support_score       float64
has_therapy                  int64
stress_level               float64
anxiety_score              float64
depression_score           float64
burnout_score              float64
burnout_level               object
seeks_professional_help      int64
dtype: object

In [19]:
print("Missing Values : ")
print(df.isnull().sum())

Missing Values :
age                        0
gender                     0
job_role                   0
experience_years           0
company_size               0
work_mode                  0
work_hours_per_week        0
overtime_hours             0
meetings_per_day           0
deadlines_missed           0
job_satisfaction           0
manager_support            0
work_life_balance          0
sleep_hours                0
physical_activity_days     0
screen_time_hours          0
caffeine_intake            0
social_support_score       0
has_therapy                0
stress_level               0
anxiety_score              0
depression_score           0
burnout_score              0
burnout_level              0
seeks_professional_help    0
dtype: int64

In [20]:
print("Duplicate rows : ",df.duplicated().sum())

Duplicate rows :  0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      150000 non-null  int64
 1   gender                   150000 non-null  object
 2   job_role                 150000 non-null  object
 3   experience_years         150000 non-null  float64
 4   company_size             150000 non-null  object
 5   work_mode                150000 non-null  object
 6   work_hours_per_week      150000 non-null  float64
 7   overtime_hours           150000 non-null  float64
 8   meetings_per_day         150000 non-null  float64
 9   deadlines_missed         150000 non-null  int64
 10  job_satisfaction         150000 non-null  float64
 11  manager_support          150000 non-null  float64
 12  work_life_balance        150000 non-null  float64
 13  sleep_hours              150000 non-null  float64
 14  physical_activity_days   150000 non-null  int64
 15  screen_time_hours        150000 non-null  float64
 16  caffeine_intake          150000 non-null  int64
 17  social_support_score     150000 non-null  float64
 18  has_therapy              150000 non-null  int64
 19  stress_level             150000 non-null  float64
 20  anxiety_score            150000 non-null  float64
 21  depression_score         150000 non-null  float64
 22  burnout_score            150000 non-null  float64
 23  burnout_level            150000 non-null  object
 24  seeks_professional_help  150000 non-null  int64
dtypes: float64(14), int64(6), object(5)
memory usage: 28.6+ MB

In [22]:
df.describe(include="all")

,age,gender,job_role,experience_years,company_size,work_mode,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,...,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,burnout_level,seeks_professional_help
count,150000.000000,150000,150000,150000.000000,150000,150000,150000.00000,150000.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000,150000.000000
unique,NaN,3,8,NaN,4,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
top,NaN,Male,Software Engineer,NaN,Large,Hybrid,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN
freq,NaN,82286,37623,NaN,37623,60056,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131620,NaN
mean,38.025340,NaN,NaN,5.055010,NaN,NaN,47.00758,6.127180,4.010893,1.284193,...,8.002713,2.101693,5.498163,0.251133,5.785428,4.523763,3.096687,2.114121,NaN,0.096333
std,9.510609,NaN,NaN,2.878602,NaN,NaN,7.89331,3.783618,1.978316,1.426264,...,1.987813,1.300247,1.957432,0.433667,1.331506,1.201506,1.187668,1.112614,NaN,0.295049
min,22.000000,NaN,NaN,0.000000,NaN,NaN,30.00000,0.000000,0.000000,0.000000,...,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000
25%,30.000000,NaN,NaN,3.000000,NaN,NaN,42.00000,3.000000,3.000000,0.000000,...,6.700000,1.000000,4.200000,0.000000,4.900000,3.700000,2.200000,1.000000,NaN,0.000000
50%,38.000000,NaN,NaN,5.000000,NaN,NaN,47.00000,6.000000,4.000000,1.000000,...,8.000000,2.000000,5.500000,0.000000,5.800000,4.500000,3.100000,1.900000,NaN,0.000000
75%,46.000000,NaN,NaN,7.000000,NaN,NaN,52.00000,9.000000,5.000000,2.000000,...,9.300000,3.000000,6.800000,1.000000,6.700000,5.300000,3.900000,2.800000,NaN,0.000000
max,54.000000,NaN,NaN,18.500000,NaN,NaN,84.00000,24.000000,12.000000,5.000000,...,16.000000,5.000000,10.000000,1.000000,10.000000,9.600000,8.100000,8.100000,NaN,1.000000

In [5]:
print(df.columns.tolist())

['age', 'gender', 'job_role', 'experience_years', 'company_size', 'work_mode', 'work_hours_per_week', 'overtime_hours', 'meetings_per_day', 'deadlines_missed', 'job_satisfaction', 'manager_support', 'work_life_balance', 'sleep_hours', 'physical_activity_days', 'screen_time_hours', 'caffeine_intake', 'social_support_score', 'has_therapy', 'stress_level', 'anxiety_score', 'depression_score', 'burnout_score', 'burnout_level', 'seeks_professional_help']

In [6]:
print(df["burnout_level"].value_counts())

burnout_level
Low         131620
Moderate     18315
High            65
Name: count, dtype: int64

In [7]:
print(df["burnout_level"].value_counts(normalize=True)*100)

burnout_level
Low         87.746667
Moderate    12.210000
High         0.043333
Name: proportion, dtype: float64

In [8]:
print(df[["burnout_score","burnout_level"]].head(20))

    burnout_score burnout_level
0             1.0           Low
1             3.7      Moderate
2             1.0           Low
3             3.6      Moderate
4             3.5           Low
5             1.0           Low
6             4.5      Moderate
7             1.0           Low
8             3.0           Low
9             1.0           Low
10            4.5      Moderate
11            2.7           Low
12            3.8      Moderate
13            2.5           Low
14            1.7           Low
15            1.0           Low
16            1.0           Low
17            3.4           Low
18            2.9           Low
19            2.7           Low

In [9]:
print(df.groupby("burnout_level")["burnout_score"].agg(["min","max","mean"]))

               min  max      mean
burnout_level
High           6.6  8.1  6.893846
Low            1.0  3.5  1.815136
Moderate       3.6  6.5  4.245804

In [10]:
print("DATASET INFORMATION")
print("=" * 50)

print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

DATASET INFORMATION
==================================================
Shape: (150000, 25)

Data Types:
age                          int64
gender                      object
job_role                    object
experience_years           float64
company_size                object
work_mode                   object
work_hours_per_week        float64
overtime_hours             float64
meetings_per_day           float64
deadlines_missed             int64
job_satisfaction           float64
manager_support            float64
work_life_balance          float64
sleep_hours                float64
physical_activity_days       int64
screen_time_hours          float64
caffeine_intake              int64
social_support_score       float64
has_therapy                  int64
stress_level               float64
anxiety_score              float64
depression_score           float64
burnout_score              float64
burnout_level               object
seeks_professional_help      int64
dtype: object

Missing Values:
age                        0
gender                     0
job_role                   0
experience_years           0
company_size               0
work_mode                  0
work_hours_per_week        0
overtime_hours             0
meetings_per_day           0
deadlines_missed           0
job_satisfaction           0
manager_support            0
work_life_balance          0
sleep_hours                0
physical_activity_days     0
screen_time_hours          0
caffeine_intake            0
social_support_score       0
has_therapy                0
stress_level               0
anxiety_score              0
depression_score           0
burnout_score              0
burnout_level              0
seeks_professional_help    0
dtype: int64

Duplicate Rows:
0

In [11]:
print("\nUnique Values")
print("=" * 50)

for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Unique Values
==================================================
age: 33
gender: 3
job_role: 8
experience_years: 172
company_size: 4
work_mode: 3
work_hours_per_week: 52
overtime_hours: 25
meetings_per_day: 13
deadlines_missed: 6
job_satisfaction: 91
manager_support: 91
work_life_balance: 91
sleep_hours: 71
physical_activity_days: 8
screen_time_hours: 127
caffeine_intake: 6
social_support_score: 91
has_therapy: 2
stress_level: 91
anxiety_score: 85
depression_score: 72
burnout_score: 67
burnout_level: 3
seeks_professional_help: 2

In [12]:
print("\nCategorical Columns")
print("=" * 50)

categorical_cols = df.select_dtypes(include="object").columns.tolist()

print(categorical_cols)

Categorical Columns
==================================================
['gender', 'job_role', 'company_size', 'work_mode', 'burnout_level']

### **check for rows which can be delete from dataset**

In [13]:
duplicates = df[df.duplicated(keep=False)]

print("Duplicate rows:", len(duplicates))
display(duplicates.head(20))

Duplicate rows: 0

Empty DataFrame
Columns: [age, gender, job_role, experience_years, company_size, work_mode, work_hours_per_week, overtime_hours, meetings_per_day, deadlines_missed, job_satisfaction, manager_support, work_life_balance, sleep_hours, physical_activity_days, screen_time_hours, caffeine_intake, social_support_score, has_therapy, stress_level, anxiety_score, depression_score, burnout_score, burnout_level, seeks_professional_help]
Index: []

[0 rows x 25 columns]

In [14]:
missing_rows = df[df.isnull().any(axis=1)]

print("Rows containing missing values:", len(missing_rows))
display(missing_rows.head(20))

Rows containing missing values: 0

Empty DataFrame
Columns: [age, gender, job_role, experience_years, company_size, work_mode, work_hours_per_week, overtime_hours, meetings_per_day, deadlines_missed, job_satisfaction, manager_support, work_life_balance, sleep_hours, physical_activity_days, screen_time_hours, caffeine_intake, social_support_score, has_therapy, stress_level, anxiety_score, depression_score, burnout_score, burnout_level, seeks_professional_help]
Index: []

[0 rows x 25 columns]

In [15]:
print("Age range:")
print(df["age"].min(), df["age"].max())

print("\nExperience range:")
print(df["experience_years"].min(), df["experience_years"].max())

print("\nWork hours range:")
print(df["work_hours_per_week"].min(), df["work_hours_per_week"].max())

print("\nSleep hours range:")
print(df["sleep_hours"].min(), df["sleep_hours"].max())

print("\nScreen time range:")
print(df["screen_time_hours"].min(), df["screen_time_hours"].max())

Age range:
22 54

Experience range:
0.0 18.5

Work hours range:
30.0 84.0

Sleep hours range:
3.0 10.0

Screen time range:
3.0 16.0

### **Categorical VS numerical features**

In [16]:
# Numerical columns
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("Numerical Columns:")
print(numerical_cols)

print("\nNumber of Numerical Columns:", len(numerical_cols))

Numerical Columns:
['age', 'experience_years', 'work_hours_per_week', 'overtime_hours', 'meetings_per_day', 'deadlines_missed', 'job_satisfaction', 'manager_support', 'work_life_balance', 'sleep_hours', 'physical_activity_days', 'screen_time_hours', 'caffeine_intake', 'social_support_score', 'has_therapy', 'stress_level', 'anxiety_score', 'depression_score', 'burnout_score', 'seeks_professional_help']

Number of Numerical Columns: 20

In [17]:
# Categorical columns
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

print("Categorical Columns:")
print(categorical_cols)

print("\nNumber of Categorical Columns:", len(categorical_cols))

Categorical Columns:
['gender', 'job_role', 'company_size', 'work_mode', 'burnout_level']

Number of Categorical Columns: 5

In [18]:
print("\nUnique values of categorical columns:")

for col in categorical_cols:
    print("\n", col)
    print(df[col].value_counts())

Unique values of categorical columns:

 gender
gender
Male          82286
Female        60281
Non-binary     7433
Name: count, dtype: int64

 job_role
job_role
Software Engineer     37623
Data Scientist        22442
ML Engineer           18153
Backend Developer     18079
Frontend Developer    17967
DevOps                14897
Product Manager       11925
QA Engineer            8914
Name: count, dtype: int64

 company_size
company_size
Large       37623
Startup     37560
MNC         37461
Mid-size    37356
Name: count, dtype: int64

 work_mode
work_mode
Hybrid    60056
Remote    52471
Onsite    37473
Name: count, dtype: int64

 burnout_level
burnout_level
Low         131620
Moderate     18315
High            65
Name: count, dtype: int64

In [19]:
y = df["burnout_level"]

In [20]:
X = df.drop(columns=["burnout_level", "burnout_score"])
y = df["burnout_level"]

In [21]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,150000.0,38.025340,9.510609,22.0,30.0,38.0,46.0,54.0
experience_years,150000.0,5.055010,2.878602,0.0,3.0,5.0,7.0,18.5
work_hours_per_week,150000.0,47.007580,7.893310,30.0,42.0,47.0,52.0,84.0
overtime_hours,150000.0,6.127180,3.783618,0.0,3.0,6.0,9.0,24.0
meetings_per_day,150000.0,4.010893,1.978316,0.0,3.0,4.0,5.0,12.0
deadlines_missed,150000.0,1.284193,1.426264,0.0,0.0,1.0,2.0,5.0
job_satisfaction,150000.0,5.500248,1.956102,1.0,4.2,5.5,6.9,10.0
manager_support,150000.0,5.497537,1.956915,1.0,4.1,5.5,6.8,10.0
work_life_balance,150000.0,5.016357,1.948553,1.0,3.7,5.0,6.4,10.0
sleep_hours,150000.0,6.499120,1.192343,3.0,5.7,6.5,7.3,10.0
physical_activity_days,150000.0,2.599833,1.814880,0.0,1.0,2.0,4.0,7.0
screen_time_hours,150000.0,8.002713,1.987813,3.0,6.7,8.0,9.3,16.0
caffeine_intake,150000.0,2.101693,1.300247,0.0,1.0,2.0,3.0,5.0
social_support_score,150000.0,5.498163,1.957432,1.0,4.2,5.5,6.8,10.0
has_therapy,150000.0,0.251133,0.433667,0.0,0.0,0.0,1.0,1.0
stress_level,150000.0,5.785428,1.331506,1.0,4.9,5.8,6.7,10.0
anxiety_score,150000.0,4.523763,1.201506,1.0,3.7,4.5,5.3,9.6
depression_score,150000.0,3.096687,1.187668,1.0,2.2,3.1,3.9,8.1
burnout_score,150000.0,2.114121,1.112614,1.0,1.0,1.9,2.8,8.1
seeks_professional_help,150000.0,0.096333,0.295049,0.0,0.0,0.0,0.0,1.0

In [22]:
for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].unique())

gender:
['Female' 'Male' 'Non-binary']

job_role:
['Backend Developer' 'Frontend Developer' 'DevOps' 'Data Scientist'
 'Software Engineer' 'Product Manager' 'QA Engineer' 'ML Engineer']

company_size:
['Large' 'Mid-size' 'MNC' 'Startup']

work_mode:
['Hybrid' 'Remote' 'Onsite']

burnout_level:
['Low' 'Moderate' 'High']

# **Reduce 150K TO 30K Rows**

In [23]:
# Keep ALL High-risk records
high = df[df["burnout_level"] == "High"]

# Sample Moderate records
moderate = df[df["burnout_level"] == "Moderate"].sample(
    n=8000,
    random_state=42
)

# Sample Low records
low = df[df["burnout_level"] == "Low"].sample(
    n=21935,
    random_state=42
)

# Combine
df_30k = pd.concat([low, moderate, high], ignore_index=True)

# Shuffle
df_30k = df_30k.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print(df_30k.shape)
print(df_30k["burnout_level"].value_counts())

(30000, 25)
burnout_level
Low         21935
Moderate     8000
High           65
Name: count, dtype: int64

In [24]:
print("Dataset Shape:", df_30k.shape)

Dataset Shape: (30000, 25)

In [25]:
print("\nBurnout Distribution:")
print(df_30k["burnout_level"].value_counts())

Burnout Distribution:
burnout_level
Low         21935
Moderate     8000
High           65
Name: count, dtype: int64

In [26]:
print("\nBurnout Distribution (%):")
print(df_30k["burnout_level"].value_counts(normalize=True) * 100)

Burnout Distribution (%):
burnout_level
Low         73.116667
Moderate    26.666667
High         0.216667
Name: proportion, dtype: float64

In [27]:
print("Missing values:", df_30k.isnull().sum().sum())

Missing values: 0

In [28]:
print("Duplicate rows:", df_30k.duplicated().sum())

Duplicate rows: 0

In [30]:
X = df_30k.drop(columns=["burnout_level", "burnout_score"])

y = df_30k["burnout_level"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (30000, 23)
y shape: (30000,)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (24000, 23)
Testing data: (6000, 23)

In [32]:
print("\nTraining distribution:")
print(y_train.value_counts())

print("\nTesting distribution:")
print(y_test.value_counts())

Training distribution:
burnout_level
Low         17548
Moderate     6400
High           52
Name: count, dtype: int64

Testing distribution:
burnout_level
Low         4387
Moderate    1600
High          13
Name: count, dtype: int64

In [33]:
categorical_features = [
    "gender",
    "job_role",
    "company_size",
    "work_mode"
]

numerical_features = [
    "age",
    "experience_years",
    "work_hours_per_week",
    "overtime_hours",
    "meetings_per_day",
    "deadlines_missed",
    "job_satisfaction",
    "manager_support",
    "work_life_balance",
    "sleep_hours",
    "physical_activity_days",
    "screen_time_hours",
    "caffeine_intake",
    "social_support_score",
    "has_therapy",
    "stress_level",
    "anxiety_score",
    "depression_score",
    "seeks_professional_help"
]

print("Categorical:", len(categorical_features))
print("Numerical:", len(numerical_features))

Categorical: 4
Numerical: 19

In [34]:
print("Dataset Shape:", df_30k.shape)
print(df_30k["burnout_level"].value_counts())

Dataset Shape: (30000, 25)
burnout_level
Low         21935
Moderate     8000
High           65
Name: count, dtype: int64

In [35]:
X = df_30k.drop(columns=["burnout_level", "burnout_score"])
y = df_30k["burnout_level"]

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (24000, 23)
Testing data: (6000, 23)

In [61]:
df_30k.to_csv("../ml/data/burnout_30k.csv", index=False)

print("30K dataset saved successfully!")

30K dataset saved successfully!

In [54]:
import os

print(os.path.abspath("burnout_30k.csv"))

D:\Krisha_Job\Projects\Burnout-detection-ai\ml\burnout_30k.csv

In [57]:
import os

print(os.path.exists("../ml/data/burnout_30k.csv"))

True

## **Preprocess 30K dataset**

In [59]:
import pandas as pd

df = pd.read_csv("../ml/data/burnout_30k.csv")

print("Shape:", df.shape)
print(df.head())

Shape: (30000, 25)
   age  gender           job_role  experience_years company_size work_mode  \
0   33    Male  Software Engineer               8.8        Large    Hybrid
1   41    Male        ML Engineer               8.2          MNC    Remote
2   31    Male        ML Engineer               3.2      Startup    Hybrid
3   38  Female  Backend Developer               7.2        Large    Hybrid
4   36    Male  Backend Developer               4.5        Large    Remote

   work_hours_per_week  overtime_hours  meetings_per_day  deadlines_missed  \
0                 30.0            18.0               4.0                 1
1                 54.0            11.0               5.0                 2
2                 53.0            10.0               4.0                 2
3                 61.0             9.0               6.0                 1
4                 48.0             6.0               4.0                 1

   ...  screen_time_hours  caffeine_intake  social_support_score  has_therapy  \
0  ...                7.9                2                   7.7            0
1  ...                8.5                0                   6.0            0
2  ...                9.2                1                   3.0            0
3  ...               11.6                0                   6.1            0
4  ...                8.5                5                   6.5            0

   stress_level  anxiety_score  depression_score  burnout_score  \
0           7.1            4.6               3.2            1.9
1           5.6            4.0               2.7            3.9
2           6.6            5.7               3.5            3.7
3           7.5            7.7               2.9            4.7
4           5.3            3.6               3.9            2.9

   burnout_level  seeks_professional_help
0            Low                        0
1       Moderate                        0
2       Moderate                        0
3       Moderate                        0
4            Low                        0

[5 rows x 25 columns]

In [62]:
X = df.drop(columns=["burnout_level", "burnout_score"])
y = df["burnout_level"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (30000, 23)
y shape: (30000,)

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing :", X_test.shape)

Training: (24000, 23)
Testing : (6000, 23)

In [64]:
print("Training distribution:")
print(y_train.value_counts())

print("\nTesting distribution:")
print(y_test.value_counts())

Training distribution:
burnout_level
Low         17548
Moderate     6400
High           52
Name: count, dtype: int64

Testing distribution:
burnout_level
Low         4387
Moderate    1600
High          13
Name: count, dtype: int64

In [65]:
categorical_features = [
    "gender",
    "job_role",
    "company_size",
    "work_mode"
]

numerical_features = [
    "age",
    "experience_years",
    "work_hours_per_week",
    "overtime_hours",
    "meetings_per_day",
    "deadlines_missed",
    "job_satisfaction",
    "manager_support",
    "work_life_balance",
    "sleep_hours",
    "physical_activity_days",
    "screen_time_hours",
    "caffeine_intake",
    "social_support_score",
    "has_therapy",
    "stress_level",
    "anxiety_score",
    "depression_score",
    "seeks_professional_help"
]

print("Categorical features:", len(categorical_features))
print("Numerical features:", len(numerical_features))

Categorical features: 4
Numerical features: 19